language: node_js
node_js: '11'
sudo: enabled
dist: trusty
env:
  global:
    - ELECTRON_CACHE=$HOME/.cache/electron
    - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder
install:
  - npm i
cache:
  directories:
    - node_modules
    - $HOME/.cache/electron
    - $HOME/.cache/electron-builder
    - $HOME/.npm/_prebuilds
os:
  - linux
  - osx
  - windows

script:
  - npm run compile
