environment:
  matrix:
    - nodejs_version: '11'
install:
  - ps: Install-Product node $env:nodejs_version
  - npm install --global npm@latest
  - set PATH=%APPDATA%\npm;%PATH%
  - npm uninstall screenres
  - npm install
  - npm install -g node-gyp
matrix:
  fast_finish: true
build: off
shallow_clone: true
test_script:
  - node --version
  - npm --version
  - npm run compile
cache:
  - '%APPDATA%\npm-cache'
  - 'node_modules'
