version: 2.1

orbs:
  win: circleci/windows@1.0.0

jobs:
  build:
    docker: 
      - image: circleci/node:11
    steps:
      - checkout
      - run: npm run compile
  compile-macos:
    docker: 
      - image: circleci/node:11
    steps:
      - checkout
      - run: npm run compile
  compile-windows:
    executor: win/vs2019
    steps:
      - checkout
      - run: npm run compile
